name: Worflow to run unit tests weekly

on:
  #Run action on 0:00 UTC Sunday morning
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test_schedule:
    uns-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      # install python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # install app dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pycryptodome
          pip install pillow
      # initialize app
      - name: start server
        run: |
          python server.py >run.log 2>&1 &
      # run test cases under tests/
      - name: run test cases with pytest
        run: |
          sleep 15
          pytest -v
